auto-detect OS, lowercase x for hexa numbers
vladcc/but-how-do-it-know pull request #5
Opened 2019-03-10 16:27 UTC by k3a

This makes disassembler output numbers with lower-case x like 0xFA instead 0XFA which is more confusing.

It also attempts to auto-detect OS so it compiles on Linux with just "make" without any manual modifications.

2019-03-12 20:58 UTC, vladcc requested changes
Changing the X to lowercase makes the whole hex number lowercase, not just the x in the prefix. This is inconsistent with everything else being uppercase, so it's no go.

The OS variable effects only the binary extensions and it's supposed to be set manually (Or be set automatically by a rule or something, which I haven't figured out how to do exactly. If you know how to, please go ahead.), so it's no go like this either.

#ifdef_WIN32 I like. Lave this one and add an #elif for Linux and I'll merge it. Thanks.

2019-03-12 21:00 UTC, k3a commented
OS variable is set automatically by GNU Make, please see https://renenyffenegger.ch/notes/development/make/detect-os

2019-03-12 21:14 UTC, k3a commented
Uppercase X is strange, but you are right that it's like this everywhere so let's keep uppercase, at least for now.

OS is set to Windows_NT on Windows, I've updated that condition in the Makefile directly without using WIN as a constant. 

Added `#elseif` as you requested.

2019-03-13 20:15 UTC, vladcc approved these changes
Great, thank you. I didn't know about the Windows_NT make thing, so thanks for that as well.

2019-03-13 20:16 UTC, merged